Add `Task.result`
roc-lang/basic-webserver pull request #47
Opened 2024-04-17 22:47 UTC by lukewilliamboswell

[Zulip discussion](https://roc.zulipchat.com/#narrow/stream/304902-show-and-tell/topic/Initial.20Chaining.20Syntax/near/433559391)

## Test program

```roc 
app "test"
    packages { pf: "../platform/main.roc" }
    imports [
        pf.Stdout,
        pf.Task.{ Task },
        pf.Http.{ Request, Response },
        pf.Utc,
    ]
    provides [main] to pf

main : Request -> Task Response []
main = \req ->

    result = checkFile "bad" |> Task.result!

    when result is
        Ok Good -> Task.ok { status: 200, headers: [], body: Str.toUtf8 "GOOD" }
        Ok Bad -> Task.ok { status: 200, headers: [], body: Str.toUtf8 "BAD" }
        Err IOError -> Task.ok { status: 200, headers: [], body: Str.toUtf8 "ERROR" }     

checkFile : Str -> Task [Good, Bad] [IOError]
checkFile = \str ->
    if str == "good" then 
        Task.ok Good 
    else if str == "bad" then 
        Task.ok Bad 
    else 
        Task.err IOError
```

2024-04-19 09:38 UTC, Anton-4 requested changes
Thanks @lukewilliamboswell! Can you add two small tests?

2024-04-21 03:55 UTC, lukewilliamboswell commented
@Anton-4 I've added the program as a test, and included in the expect scripts.

2024-04-21 04:02 UTC, lukewilliamboswell commented
The CI failure with the below suggests the latest nightly hasn't been updated. We can re-run CI when nightly includes support for suffixed `when` expressions which was merged in https://github.com/roc-lang/roc/pull/6649

```
A suffixed expression did not get desugared somehow: Suffixed(
    Var {
        module_name: "Task",
        ident: "result",
    },
)
```

2024-04-22 14:14 UTC, Anton-4 approved these changes

2024-04-22 14:14 UTC, merged